application: example
version: 1-alpha
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "999d"

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /humans.txt
  static_files: static/humans.txt
  upload: static/humans.txt

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /.*
  script: lib.main.wsgi_app

libraries:
- name: jinja2
  version: "2.6"

builtins:
- deferred: off
- remote_api: off
- appstats: off

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.db
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?gae.\ds.*
- ^(.*/)?gae.\bs.*
- ^(.*/)?.*tmp$
- ^(.*/)?scripts.*
- ^(.*/)?tests.*
- ^(.*/)?docs.*
